version: '3.4'

services:
  facesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  notificationservice:


  faces.webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  ordersapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

